[package]
name = "optim-lol"
version = "0.1.0"
authors = ["JulienPerrin <julien.perrin25@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
coin_cbc = "0.1.6"